[package]
name = "mf-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mf-core = { workspace = true }
mf-datasource = { workspace = true }
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
duckdb.workspace = true
thiserror.workspace = true

[lib]
name = "mf_storage"
